import { Sunrise } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'

const MorningSummarySection = () => {
  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })

  return (
    <Card className="border-border shadow-sm">
      <CardContent className="p-5">
        {/* Card Header Row */}
        <div className="flex items-center gap-3 mb-4">
          <div className="w-9 h-9 rounded-lg bg-amber-100 flex items-center justify-center flex-shrink-0">
            <Sunrise className="w-5 h-5 text-amber-600" />
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              Morning Health Briefing
            </p>
            <p className="text-xs text-muted-foreground">Manila, Philippines · {today}</p>
          </div>
        </div>

        <Separator className="mb-4" />

        {/* AI Summary Placeholder */}
        <p className="text-sm text-foreground leading-relaxed mb-3">
          Air quality in Manila this morning is rated{' '}
          <span className="font-semibold text-orange-600">Unhealthy</span> with an AQI of 158,
          primarily driven by elevated PM2.5 concentrations from traffic and industrial emissions
          overnight. Sensitive groups including asthma patients and children should limit prolonged
          outdoor exposure, especially during the morning commute hours.
        </p>
        <p className="text-sm text-muted-foreground leading-relaxed">
          A gradual improvement is expected by midday as sea breeze patterns develop along Manila
          Bay. Consider scheduling outdoor activities for the late afternoon window between 3–5 PM
          when conditions are forecast to reach Moderate levels.
        </p>

        <Separator className="my-4" />

        {/* Gemini Badge */}
        <div className="flex items-center gap-1.5">
          <div className="w-3 h-3 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex-shrink-0" />
          <Badge variant="secondary" className="text-xs font-normal">
            Generated by Gemini AI
          </Badge>
        </div>
      </CardContent>
    </Card>
  )
}

export default MorningSummarySection
