import { useEffect, useState } from 'react'
import { Sunrise, Loader2 } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import { trpc } from '@/lib/trpc'
import { useAuth } from '@/hooks/useAuth'

// ── Cache helpers (localStorage, 1-hour TTL, keyed by city) ──────────────────

const CACHE_TTL_MS = 60 * 60 * 1000 // 1 hour

function getCached(city: string): string | null {
  try {
    const raw = localStorage.getItem(`morning_briefing:${city}`)
    if (!raw) return null
    const { answer, cachedAt } = JSON.parse(raw) as { answer: string; cachedAt: number }
    if (Date.now() - cachedAt > CACHE_TTL_MS) return null
    return answer
  } catch {
    return null
  }
}

function setCached(city: string, answer: string) {
  try {
    localStorage.setItem(
      `morning_briefing:${city}`,
      JSON.stringify({ answer, cachedAt: Date.now() })
    )
  } catch {
    /* ignore storage quota errors */
  }
}

// ── Component ─────────────────────────────────────────────────────────────────

interface MorningSummarySectionProps {
  homeCity?: string | null
}

const MorningSummarySection = ({ homeCity }: MorningSummarySectionProps) => {
  const { user, loading } = useAuth()
  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })

  const [cachedAnswer, setCachedAnswer] = useState<string | null>(null)

  const {
    mutate: fetchBriefing,
    isPending,
    data,
    isError,
  } = trpc.chat.ask.useMutation({
    onSuccess: result => {
      if (homeCity) setCached(homeCity, result.answer)
    },
  })

  useEffect(() => {
    if (loading) return
    if (!user) return
    if (!homeCity) return

    // Serve from cache if still fresh
    const cached = getCached(homeCity)
    if (cached) {
      setCachedAnswer(cached)
      return
    }

    // Cache miss — fetch from RAGService
    fetchBriefing({
      question: `Give me a morning air quality briefing for ${homeCity}. Include the current air quality rating and PM2.5 levels, health recommendations especially for sensitive groups, and the short-term forecast for today.`,
      city: homeCity,
    })
  }, [homeCity, fetchBriefing, loading, user])

  const answer = cachedAnswer ?? data?.answer

  return (
    <Card className="border-border shadow-sm">
      <CardContent className="p-5">
        {/* Card Header Row */}
        <div className="flex items-center gap-3 mb-4">
          <div className="w-9 h-9 rounded-lg bg-amber-100 flex items-center justify-center flex-shrink-0">
            <Sunrise className="w-5 h-5 text-amber-600" />
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              Morning Health Briefing
            </p>
            <p className="text-xs text-muted-foreground">
              {homeCity ?? 'Set your location'} · {today}
            </p>
          </div>
        </div>

        <Separator className="mb-4" />

        {/* Loading */}
        {isPending && !answer && (
          <div className="flex items-center gap-2 text-sm text-muted-foreground py-2">
            <Loader2 className="w-4 h-4 animate-spin flex-shrink-0" />
            Generating your morning briefing…
          </div>
        )}

        {/* Answer (live or from cache) */}
        {answer && (
          <p className="text-sm text-foreground leading-relaxed whitespace-pre-line">{answer}</p>
        )}

        {/* Error */}
        {!isPending && isError && !answer && (
          <p className="text-sm text-muted-foreground">
            Unable to load briefing. Please refresh the page.
          </p>
        )}

        {/* No city set */}
        {!isPending && !answer && !isError && (
          <p className="text-sm text-muted-foreground">
            Set your home city to get a personalised morning briefing.
          </p>
        )}

        <Separator className="my-4" />

        {/* Gemini Badge */}
        <div className="flex items-center gap-1.5">
          <div className="w-3 h-3 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex-shrink-0" />
          <Badge variant="secondary" className="text-xs font-normal">
            Generated by Gemini AI
          </Badge>
        </div>
      </CardContent>
    </Card>
  )
}

export default MorningSummarySection
